const REDISCACHEHOSTNAME = "webapp-engage.redis.cache.windows.net";
const REDISCACHEKEY = "7YdKHwKy6QeopiBd1cF2kfaLAZhf4HjlzqSzCScqwJs=";
const REDISPORT = 6380;

module.exports = {REDISCACHEHOSTNAME: REDISCACHEHOSTNAME, REDISCACHEKEY:REDISCACHEKEY, REDISPORT: REDISPORT}